window.onload=function(){window.game=new Game(800,640,{acc:.5,swapSpeed:4,fastSwapSpeed:6,adviceTimeout:1E4,levels:[{colors:[6,7,8,9],tileScore:5,winScore:2E3,sizeX:7,sizeY:7,time:90},{colors:[0,1,2,3,4,5],winScore:1500,tileScore:5,sizeX:5,sizeY:8,time:200},{colors:[6,7,8,9],tileScore:5,winScore:2E3,sizeX:6,sizeY:4,time:90}]});setTimeout(function(){game.onResize()},100)};
function Game(a,b,c){Tile.app=this;this.width=a;this.height=b;for(var d in c)this[d]=c[d];this.wrapper=$("wrapper");this.offsetTop=this.wrapper.offsetTop;this.offsetLeft=this.wrapper.offsetLeft;this.layers={back:new Layer($("back"),a,b,1),squares:new Layer($("squares"),a,b,2),cursor:new Layer($("cursor"),a,b,3)};this.images={tiles:$("img-tiles")};this.sounds={};this.addListeners();this.loadLevel(0);this.animate();this.trigger("gameStart")}
Game.prototype={level:null,levels:[],acc:.3,swapSpeed:4,fastSwapSpeed:6,adviceTimeout:1E4,gridWidth:600,padding:20,cellBorder:1,comboSize:0,maxCombo:0,scores:0,moves:0,activePoint:{x:0,y:0},activeTile:{x:-999,y:-999},colors:{plateA:"#58758c",plateB:"#373b5b",activeTile:"#fff",selectedTile:"#fc0",adviceTile:"#5f5"},colsToUpdate:[],fallingTiles:[],swappingTiles:[],timerTimeout:null,timer:0,startLevelUpdate:!1,lastAction:(new Date).getTime(),startTiles:[],checkComboQueue:[],comboIsRunning:!1,MOUSE_HOLDED:!1,
events:{swapSuccess:function(){this.increaseMoves()},swapFail:function(){},swapFinish:function(){},tilesExplode:function(a){},comboExplode:function(a){this.comboSize++},multiComboEnd:function(a){a>this.maxCombo&&(this.maxCombo=a,this.drawMaxCombo())},gameStart:function(){},levelStart:function(){},scoresAdded:function(){},timeFinish:function(){},win:function(){}},trigger:function(){var a=Array.prototype.slice.call(arguments),b=a[0];b&&"undefined"!==typeof this.events[b]&&this.events[b].apply(this,
a.slice(1))},updateColsTiles:function(a){for(var b={},c=[],d=0,f=a.length;d<f;++d)b.hasOwnProperty(a[d])||(c.push(a[d]),b[a[d]]=1);for(d=0;d<c.length;d++)this.colsToUpdate.push(c[d])},loadLevel:function(a){this.layers.cursor.empty();this.level="undefined"!==typeof this.levels[a]?this.levels[a]:this.levels[0];this.cellSize=this.level.sizeX>this.level.sizeY?Math.floor(this.gridWidth/this.level.sizeX):this.level.sizeX<this.level.sizeY?Math.floor(this.gridWidth/this.level.sizeY):Math.floor(this.gridWidth/
this.level.sizeX);this.tilePadding=10;this.tileSize=this.cellSize-2*this.tilePadding;this.colsToUpdate=[];this.fallingTiles=[];this.swappingTiles=[];this.checkComboQueue=[];this.maxCombo=this.moves=this.scores=0;this.resetTimer();this.drawBackground();this.drawScores();this.drawMaxCombo();this.drawTimer();this.drawMoves();this.clearTiles();this.generateTiles();this.draw();a=[];for(var b=0;b<this.level.sizeX;b++)a.push(b);this.updateColsTiles(a);this.startLevelUpdate=!0;this.trigger("levelStart")},
resetTimer:function(){clearTimeout(this.timerTimeout);this.timer=this.level.time;this.updateTimer()},updateTimer:function(){this.timer--;0>this.timer?(this.timer=0,this.trigger("timeFinish")):(this.drawTimer(),this.timerTimeout=setTimeout(function(){this.updateTimer()}.bind(this),1E3))},increaseMoves:function(){this.moves++;this.drawMoves()},addStartTile:function(a){"undefined"===typeof this.startTiles[a.gridX]&&(this.startTiles[a.gridX]=[]);var b=this.getUnsafeColors(a);b.length&&(a.color=this.generateSafeColor(b));
this.startTiles[a.gridX][a.gridY]=a},getUnsafeColors:function(a){var b=[],c=a.gridX;a=a.gridY;for(var d,f=0;f<this.level.colors.length;f++){d=this.level.colors[f];for(var e=-1;1>=e;e++)for(var h=-1;1>=h;h++)1==Math.abs(h+e)&&(levelOne=this.getStartTile(c+e,a+h))&&levelOne.color==d&&(levelTwo=this.getStartTile(c+2*e,a+2*h))&&levelTwo.color==d&&b.push(d)}return b},generateSafeColor:function(a){a=array_diff(this.level.colors,a);var b=rand(0,a.length-1);return a[b]},getStartTile:function(a,b){return"undefined"!==
typeof this.startTiles[a]&&"undefined"!==typeof this.startTiles[a][b]?this.startTiles[a][b]:null},generateTiles:function(){var a=this.level.sizeX,b=this.level.sizeY,c,d;0!=a%2&&a++;0!=b%2&&b++;a>b?b=a:a<b&&(a=b);c=[[a/2-1,b/2-1],[a/2-1,b/2],[a/2,b/2-1],[a/2,b/2]];for(d=0;d<c.length;d++)this.addStartTile(this.generateTile(c[d][0],c[d][1]));for(var f=a/2,e=1;e<f;e++){d=b/2-(e+1);for(c=a/2-e;c<a/2+e;c++)this.addStartTile(this.generateTile(c,d));d=b/2+e;for(c=a/2-e;c<a/2+e;c++)this.addStartTile(this.generateTile(c,
d));c=a/2-(e+1);for(d=b/2-e;d<b/2+e;d++)this.addStartTile(this.generateTile(c,d));c=a/2+e;for(d=b/2-e;d<b/2+e;d++)this.addStartTile(this.generateTile(c,d));d=b/2-(e+1);c=a/2-(e+1);this.addStartTile(this.generateTile(c,d));d=b/2+e;c=a/2+e;this.addStartTile(this.generateTile(c,d));d=b/2-(e+1);c=a/2+e;this.addStartTile(this.generateTile(c,d));d=b/2+e;c=a/2-(e+1);this.addStartTile(this.generateTile(c,d))}},clearTiles:function(){this.tiles=[];for(var a=0;a<this.level.sizeX;a++){this.tiles[a]=[];for(var b=
0;b<this.level.sizeY;b++)this.tiles[a][b]=this.generateEmptyTile(a,b)}},generateTile:function(a,b){var c=rand(0,this.level.colors.length-1);return new Tile(this.level.colors[c],a,b)},generateEmptyTile:function(a,b){var c=new Tile(0,a,b);c.empty=!0;return c},animate:function(){this.update()&&this.draw();this.updateScores&&(this.updateScores=!1,this.drawScores());var a=(new Date).getTime();this.lastAction&&a-this.lastAction>this.adviceTimeout&&this.advice();setTimeout(function(){this.animate()}.bind(this),
1E3/60)},checkTilesInColumn:function(a,b,c){for(var d=0,f=b;0<=f;f--)a[b].empty&&(d++,"undefined"!==typeof a[b+1]&&(a[b+1].gridY+=c+1,d+=this.checkTilesInColumn(a,b+1,c+1)));return d},swapTiles:function(a,b,c){if(a&&b){var d=a.gridY-b.gridY,f=a.gridX-b.gridX;if(1==Math.abs(d)+Math.abs(f)){var e=c?this.fastSwapSpeed:this.swapSpeed,h=a.gridX,g=a.gridY;a.targetX=b.x;a.targetY=b.y;a.gridX=b.gridX;a.gridY=b.gridY;a.speedX=-f*e;a.speedY=-d*e;b.targetX=a.x;b.targetY=a.y;b.gridX=h;b.gridY=g;b.speedX=f*e;
b.speedY=d*e;this.swappingTiles=[a,b];this.reverseSwap=c?!0:!1;return!0}return!1}},checkForCombo:function(a,b){for(var c=[{x:0,y:1},{x:1,y:0}],d=a.adviceColor?a.adviceColor:a.color,f,e,h,g=[],k=0;k<c.length;k++){var l=1;f=c[k];for(var m=[{x:a.gridX,y:a.gridY}];e=this.getTile(a.gridX+l*f.x,a.gridY+l*f.y);){h=e.adviceColor?e.adviceColor:e.color;if(!e||e.falling||h!=d)break;m.push({x:a.gridX+l*f.x,y:a.gridY+l*f.y});l++}for(l=1;e=this.getTile(a.gridX-l*f.x,a.gridY-l*f.y);){h=e.adviceColor?e.adviceColor:
e.color;if(!e||e.falling||h!=d)break;m.push({x:a.gridX-l*f.x,y:a.gridY-l*f.y});l++}2<m.length&&g.push(m)}if(b)return g;if(g.length){c=[];for(k=d=0;k<g.length;k++){f=g[k];e=!0;for(h=0;h<f.length;h++)this.getTile(f[h].x,f[h].y).empty?e=!1:(this.getTile(f[h].x,f[h].y).empty=!0,this.addScoreForCombo(f.length),c.push(f[h].x));e&&(d++,this.trigger("tilesExplode",f))}d&&this.trigger("comboExplode",g);this.runCombo();this.updateColsTiles(c)}return 0<g.length},runCombo:function(){this.comboIsRunning=this.DISABLE_MOUSE=
!0},endCombo:function(){this.DISABLE_MOUSE=this.comboIsRunning=!1;for(var a=0;a<this.colsToCheck.length;a++)this.checkColumnForCombo(this.colsToCheck[a]);this.comboIsRunning||(this.trigger("multiComboEnd",this.comboSize),this.comboSize=0)},checkColumnForCombo:function(a){for(var b=this.level.sizeY-1;0<=b&&!this.checkForCombo(this.getTile(a,b));b--);},addScoreForCombo:function(a){var b=this.level.tileScore;3<a&&(b=Math.round(b*a/2));this.trigger("scoresAdded");this.scores+=b;this.scores>=this.level.winScore&&
this.trigger("win");this.updateScores=!0},advice:function(){this.hideAdvice();for(var a=0;a<this.level.sizeX;a++)for(var b=this.level.sizeY-1;0<=b;b--)if(this.checkPossibleCombo(a,b)){this.showAdvice(a,b);return}},hideAdvice:function(){this.drawAdvice=!1;this.drawActiveTile()},showAdvice:function(a,b){this.drawAdvice={x:a,y:b};this.drawActiveTile()},checkPossibleCombo:function(a,b){var c=this.getTile(a,b),d=c.color,f,e,h,g,k;for(f=-1;1>f;f+=1)for(e=-1;1>=e;e+=1)if(1==Math.abs(e+f)&&(h=this.getTile(a+
f,b+e))&&(c.color=h.color,h.color=d,g=this.checkForCombo(c,!0),k=this.checkForCombo(h,!0),h.color=c.color,c.color=d,g.length||k.length))return!0},onTileFall:function(a){},getTile:function(a,b){return"undefined"!==typeof this.tiles[a]&&"undefined"!==typeof this.tiles[a][b]?this.tiles[a][b]:null},update:function(){var a=!1;if(this.colsToUpdate.length){this.colsToUpdate=this.colsToUpdate.sort(function(a,b){return a-b});for(var b,c,d=0;d<this.colsToUpdate.length;d++){b=this.colsToUpdate[d];c=this.tiles[b];
for(var f=0,e=[],h=!1,g=this.level.sizeY-1;0<=g;g--)if(c[g].empty){if(f++,!h)for(var k=g;0<=k;k--)if(!c[k].empty){h=!0;c[k].falling=!0;c[k].speedY=0;break}}else c[g].speedY=0,e.push(c[g]);c=-this.cellSize;for(g=this.level.sizeY-1;g>=this.level.sizeY-f;g--)k=this.startLevelUpdate?this.getStartTile(b,g):this.generateTile(b,g),k.y=c,e.push(k),c-=this.tileSize;e=e.reverse();for(g=0;g<e.length;g++)e[g].gridY=g;if(!h&&f)e[f-1].falling=!0,e[f-1].speedY=0,this.fallingTiles.push({x:b,y:f-1});else for(k=0;k<
this.level.sizeY;k++)e[k].falling&&this.fallingTiles.push({x:b,y:k});this.tiles[b]=e}this.colsToCheck=this.colsToUpdate;this.colsToUpdate=[];this.startLevelUpdate&&(this.startLevelUpdate=!1)}if(this.checkComboQueue.length){for(g=0;g<this.checkComboQueue.length;g++)this.checkForCombo(this.checkComboQueue[g]);this.checkComboQueue=[]}if(this.fallingTiles.length){b=[];for(g=0;g<this.fallingTiles.length;g++)d=this.fallingTiles[g],a=this.tiles[d.x][d.y],f=5*this.acc,0!=a.gridY&&!a.foundUpper&&a.speedY>=
f&&(f=this.tiles[d.x][d.y-1],"undefined"!==typeof f&&(a.foundUpper=!0,f.falling=!0,f.speedY=0,b.push({x:f.gridX,y:f.gridY}))),a.speedY+=this.acc,10<a.speedY&&(a.speedY=10),a.y+=a.speedY,a.y>=a.getY()?(a.y=a.getY(),a.falling=!1,a.speedY=0,a.foundUpper=!1,this.onTileFall(a)):b.push(d),a=!0;this.fallingTiles=b;0==b.length&&this.endCombo()}if(this.swappingTiles.length){b=!1;for(g=0;2>g;g++)if(a=this.swappingTiles[g],0!=a.speedX){if(a.x+=a.speedX,0>a.speedX&&a.x<=a.targetX||0<a.speedX&&a.x>=a.targetX)a.x=
a.targetX,a.speedX=0,a.targetX=0,a.targetY=0,b=!0}else if(a.y+=a.speedY,0<a.speedY&&a.y>=a.targetY||0>a.speedY&&a.y<=a.targetY)a.y=a.targetY,a.speedY=0,a.targetX=0,a.targetY=0,b=!0;b&&(this.trigger("swapFinish"),a=this.swappingTiles[0],g=this.swappingTiles[1],this.tiles[a.gridX][a.gridY]=a,this.tiles[g.gridX][g.gridY]=g,this.swappingTiles=[],this.reverseSwap||(b=this.checkForCombo(a),d=this.checkForCombo(g),b||d?(this.trigger("swapSuccess"),this.drawAdvice&&this.hideAdvice()):(this.trigger("swapFail"),
game.swapTiles(g,a,!0))));a=!0}return a},click:function(){!this.DISABLE_MOUSE&&this.activeTile&&(this.selectedTile?(this.lastAction=(new Date).getTime(),this.swapTiles(this.getTile(this.selectedTile.x,this.selectedTile.y),this.getTile(this.activeTile.x,this.activeTile.y)),this.selectedTile=null):this.selectedTile={x:this.activeTile.x,y:this.activeTile.y},this.drawActiveTile())},drawBackground:function(){this.layers.back.empty();this.layers.back.setProperties({fillStyle:"#777"});this.layers.back.fillRect(0,
0,this.width,this.height);this.layers.back.setProperties({fillStyle:this.colors.plateA});this.layers.back.fillRect(this.padding,this.padding,this.gridWidth,this.gridWidth);this.layers.back.setProperties({fillStyle:this.colors.plateB});for(var a=0;a<this.level.sizeX;a++)for(var b=0;b<this.level.sizeY;b++)this.layers.back.fillRect(this.padding+a*this.cellSize+this.cellBorder,this.padding+b*this.cellSize+this.cellBorder,this.cellSize-2*this.cellBorder,this.cellSize-2*this.cellBorder)},drawTile:function(a,
b){var c=this.tiles[a][b];c.empty||this.layers.squares.drawImage(this.images.tiles,100*c.color,0,100,100,c.x,c.y,this.tileSize,this.tileSize)},draw:function(){this.layers.squares.empty();for(var a=0;a<this.level.sizeX;a++)for(var b=0;b<this.level.sizeY;b++)this.drawTile(a,b)},drawActiveTile:function(){this.layers.cursor.empty();this.drawAdvice&&(this.layers.cursor.setProperties({fillStyle:this.colors.adviceTile}),this.layers.cursor.fillRect(this.padding+this.drawAdvice.x*this.cellSize,this.padding+
this.drawAdvice.y*this.cellSize,this.cellSize,this.cellSize),this.layers.cursor.clearRect(this.padding+this.drawAdvice.x*this.cellSize+5,this.padding+this.drawAdvice.y*this.cellSize+5,this.cellSize-10,this.cellSize-10));this.selectedTile&&(this.layers.cursor.setProperties({fillStyle:this.colors.selectedTile}),this.layers.cursor.fillRect(this.padding+this.selectedTile.x*this.cellSize,this.padding+this.selectedTile.y*this.cellSize,this.cellSize,this.cellSize),this.layers.cursor.clearRect(this.padding+
this.selectedTile.x*this.cellSize+5,this.padding+this.selectedTile.y*this.cellSize+5,this.cellSize-10,this.cellSize-10));this.activeTile&&(this.layers.cursor.setProperties({fillStyle:this.colors.activeTile}),this.layers.cursor.fillRect(this.padding+this.activeTile.x*this.cellSize,this.padding+this.activeTile.y*this.cellSize,this.cellSize,this.cellSize),this.layers.cursor.clearRect(this.padding+this.activeTile.x*this.cellSize+5,this.padding+this.activeTile.y*this.cellSize+5,this.cellSize-10,this.cellSize-
10))},drawScores:function(){$("scores-value").innerHTML=this.scores},drawTimer:function(){$("timer-value").innerHTML=this.formatTime(this.timer)},drawMoves:function(){$("moves-value").innerHTML=this.moves},drawMaxCombo:function(){$("combo-value").innerHTML=this.maxCombo},formatTime:function(a){var b=Math.floor(a/60)+":";a%=60;10>a&&(a="0"+a);return b+a},addListeners:function(){this.wrapper.addEventListener("mousedown",function(a){this.updateActivePoint(a);this.MOUSE_HOLDED=!0;this.click()}.bind(this));
this.wrapper.addEventListener("mousemove",function(a){this.updateActivePoint(a)}.bind(this));this.wrapper.addEventListener("mouseup",function(a){this.MOUSE_HOLDED=!1}.bind(this));this.wrapper.addEventListener("touchstart",function(a){this.updateActivePoint(a.touches[0]);this.MOUSE_HOLDED=!0}.bind(this));this.wrapper.addEventListener("touchmove",function(a){a.preventDefault();this.updateActivePoint(a.touches[0])}.bind(this));this.wrapper.addEventListener("touchend",function(a){this.MOUSE_HOLDED=!1}.bind(this));
this.wrapper.addEventListener("touchcancel",function(a){this.MOUSE_HOLDED=!1}.bind(this));window.addEventListener("resize",function(){this.onResize()}.bind(this),!1);window.addEventListener("orientationchange",function(){this.onResize()}.bind(this),!1);this.wrapper.addEventListener("click",function(a){}.bind(this))},updateActivePoint:function(a){var b=this.wrapper.clientHeight/this.height;this.activePoint.x=Math.floor((a.pageX-this.offsetLeft)/(this.wrapper.clientWidth/this.width));this.activePoint.y=
Math.floor((a.pageY-this.offsetTop)/b);a=Math.floor((this.activePoint.x-this.padding)/this.cellSize);b=Math.floor((this.activePoint.y-this.padding)/this.cellSize);a=a>this.level.sizeX-1||b>this.level.sizeY-1||0>a||0>b?{x:-999,y:-999}:{x:a,y:b};if(this.activeTile.x!=a.x||this.activeTile.y!=a.y)this.activeTile=a,this.drawActiveTile()},onResize:function(){var a=window.innerWidth,b=window.innerHeight;1.25<a/b?(a=1.25*b,this.wrapper.style.height=b+"px",this.wrapper.style.width=a+"px"):(b=a/1.25,this.wrapper.style.width=
a+"px",this.wrapper.style.height=b+"px");this.wrapper.style.marginTop=-b/2+"px";this.wrapper.style.marginLeft=-a/2+"px";$("el-timer").style.fontSize=.04*a+"px";$("el-scores").style.fontSize=.04*a+"px";$("el-moves").style.fontSize=.04*a+"px";$("el-combo").style.fontSize=.04*a+"px";this.offsetTop=this.wrapper.offsetTop;this.offsetLeft=this.wrapper.offsetLeft}};